import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import bg from "../public/assets/images/102058-OM2YGT-343_2.jpg"
import { GetSetUpPageById } from "./setuppage/api/setuppageAPI";

const inter = Inter({ subsets: ["latin"] });

export async function metadata(): Promise<Metadata> {
  const response = await GetSetUpPageById(1)
  const result = await response
  const meta = {
    title: "App Artical",
    description: "Generated by create next app",
    keywords: ['app', 'mobile', 'phone', 'artical'],
    // icons: {
    //   icon: [
    //     'http://localhost:8000/uploads/icon/icon.png'
    //   ]
    // }
  }

  if (result?.data)
  {
    meta.title = result.data.title
    meta.description = result.data.description
    const stringKeywords = result.data.keywords?.split([","])
    console.log(stringKeywords)
    meta.keywords = stringKeywords? stringKeywords : meta.keywords
  }

  return {
    title: meta.title,
    description: meta.description,
    keywords: meta.keywords
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const response = await fetch(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/getBannerByIsActive`)
  const result = await response.json()
  let image
  if (result.data.length == 0) {
    image = bg
  }
  else {
    const response = await fetch(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/getBannerByIsActive`)
    const result = await response.json()
    image = {
      'src': result.data ? process.env.NEXT_PUBLIC_BACKEND_URL + '/' + result.data.image_file : '',
    }
  }
  return (
    <html lang="en" data-theme="mytheme1">
      <body className={inter.className}>
        <div className={`w-full h-72 bg-center bg-no-repeat bannerImage`} style={{ backgroundImage: `url(${image.src})`, width: '100%', height: '288px' }}>
          <div className="w-full h-full opacity-80">
            <Navbar />
          </div>
        </div>

        {children}
        <Footer />
      </body>
    </html>
  );
}
